'use client'
import { useState } from "react";

interface PlayerFormProps {
  onSubmit: (playerName: string, otherInfo: string) => void;
}

export default function PlayerForm({ onSubmit }: PlayerFormProps) {
  const [playerName, setPlayerName] = useState<string>('');
  const [adventureName, setAdventureName] = useState<string>('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (playerName.trim()) {
      onSubmit(playerName, adventureName);
    }
    else {
      alert('Please enter a name');
    }
  };

return(
  <div className="min-h-screen flex justify-center items-center w=1/2">  
    <form onSubmit={handleSubmit} className="">
      <h2 className="text-5xl">Enter your details to start the adventure</h2>
        <div className="py-5">
          <input
            type="text"
            placeholder="Enter your name"
            value={playerName}
            onChange={(e) => setPlayerName(e.target.value)}
            className="border p-2 w-full text-black"
          />
        </div>
        <div className="pb-5">
          <input
            type="text"
            placeholder="Adventure Info (Leave blank for a custom adventure generated by AI)"
            value={adventureName}
            onChange={(e) => setAdventureName(e.target.value)}
            className="border p-2 w-full text-black"
          />
        </div>
        <button
          type="submit"
          className="bg-white text-black rounded-md p-1 px-5 text-xl hover:bg-yellow-400 hover:scale-105"
        >
          Begin Adventure
        </button>
    </form>
  </div>

);
}
